### ISSUE TITLE
Boom.badGateway( string, Boom.anything() )

### ISSUE THREAD

**Issue by jmonster** [hapijs/boom#152]
**Preface: Our use case may not be your use case; it's understood you may disagree with this concern.** That said...

We're using promises in our codebase. So imagine a scenario like the following...

```js
wreckAsPromised.get('https://...')
  .then((response) => { ... })
  .catch((err) => {
    // this is where things go badly vvv
    throw Boom.badGateway('Unable to reach some endpoint', err);
  });
```

Our server reports all errors that we `reply()` with to Rollbar. So, it's important for us to
1. return a decent human message like 'Unable to reach the API'
2. capture actual error data so we may be debug/fix issues

But this code fails because of this behavior:
+ https://github.com/hapijs/boom/blob/master/lib/index.js#L76
+ https://github.com/hapijs/boom/blob/master/lib/index.js#L94

I expect changing this will be very controversial but wanted to highlight the concern regardless.

---

cc @tevanoff

**Comment by arb** [comment]
Did you have a proposed solution or did you just want to start a conversation about possible solutions?

**Comment by tevanoff** [comment]
@arb after looking at this a bit more, it looks like the root of the problem is this: https://github.com/hapijs/boom/blob/master/lib/index.js#L392

We haven't tested it out thoroughly, but if we change that to `if (data instanceof Error && !data.isBoom) {` it fixes the problem we're seeing since it avoids trying to wrap `data` when it's a Boom instance and just sets it on the created Boom instance as we were expecting.

We can test it out a bit more and open a PR if that sounds like a viable solution to you. Happy to hear if you have thoughts on a better solution too.

Thanks!

**Comment by camfraser** [comment]
@tevanoff alternatively, you could adjust your call to `Boom.badGateway` to wrap the rejected data in an error. This is a technique I use regularly in our promise-based repos.
```
wreckAsPromised.get('https://...')
  .then((response) => { ... })
  .catch((err) => {
    // this is where things go badly vvv
    throw Boom.badGateway('Unable to reach some endpoint', new Error(err));
  });
```

**Comment by jmonster** [comment]
I appreciate the suggestions, but our underlying goal is to capture the original error's stack trace. The [Boom docs](https://github.com/hapijs/boom/blob/master/README.md#boombadgatewaymessage-data) specify that arbitrary data can be passed in as the second parameter yet there exists some data that it doesn't like (i.e. anything with `isBoom: true`).

So I think we have either a bug in the code or a bug in the docs?

@arb is there any reason not to apply @tevanoff's suggested fix at a minimum?

**Comment by WesTyler** [comment]
So is the problem coming from the case when the `err` that gets caught is itself a Boom error object? Or do `TypeError`s and other Node.js `Error` objects also cause a problem?

**Comment by tevanoff** [comment]
@WesTyler yeah, it's when the `err` is a Boom and we try to pass that in as the `data` attribute on another Boom object.  But it only seems to break when using the 5xx error helpers.

For example, this is the case that started breaking for us:
```
error = Boom.badImplementation('badImpl');
Boom.badGateway('badGateway', error);
> Uncaught Error: Cannot provide statusCode or message with boom error
```

However, doing the same thing using create does work:
```
error = Boom.badImplementation('badImpl');
e = Boom.create(502, 'badGateway', error);
e.data
> Error: badImpl
```

The 4xx error helpers also seem to work fine:
```
error = Boom.badImplementation('badImpl');
e = Boom.notFound('notFound', error);
e.data
> Error: badImpl
```

I'm not sure if there's a reason for the different behaviors between `Boom.create()` and `Boom.badGateway()` and the like, but we started using `Boom.create()` since it works as we'd expect when passing an object in as a the data attribute. 

Any thoughts on why the 5xx error helpers seem to go through a different path? Thanks!

**Comment by AJamesPhillips** [comment]
@tevanoff that is an interesting question but also I'm curious what the use case is for changing the type of the error?  If it's a 500, 501, or 502 why not just return that?

**Comment by jmonster** [comment]
Our API makes calls to another API. When that service returns a 5XX it is incorrect for our server to propagate the response; our server did _not_ error, it received an error from an upstream service. We want to reply with a `502` in that scenario -- for example.

As of wreck v12, 4XX responses are also considered errors. We _do_ generally want to propagate those statuses, but we want to return meaningful semantics to our clients -- e.g. "Unable to fetch favorites" -- rather than the message from one of many API calls that are involved in identifying favorites.

We also don't want to return low-level details or stack traces; instead, we want simply human readable messages _but_ we also want those low level details in our `err` object because we have a plugin [icecreambar](https://github.com/yayuhh/icecreambar) that will propagate low-level error data to Rollbar from any `reply(err)` call

**Comment by WesTyler** [comment]
This is my own personal speculation and not fact, so take it with a hefty handful of salt.

I think the discrepancy between 4xx and 5xx behavior is that for 5xx server errors you *typically* are not trying to expose details to the requesting client. Additionally, for server errors, you are usually catching JS errors. I would expect 4xx responses from outside APIs to be handled specifically in an error block prior to landing in an ImplementationError catch.

Another opinionated thought is that when you receive a 4xx error from an outside API, is that really a server error on your part? To me, a 502 indicates connectivity errors or some other 5xx error from the downstream API.

**Comment by hueniverse** [comment]
If you are passing a boom object into another, you clear mean to use it as data, not as the foundation for a new error. This is a bug.
