### ISSUE TITLE
deleted

### ISSUE THREAD

**Issue by niftylettuce** [hapijs/boom#179]

**Comment by niftylettuce** [comment]
Furthermore, our usage of `hoek` does not even use the `wait` nor `block` functions that require Promises.

**Comment by niftylettuce** [comment]
Also, the `hoek` `wait` and `block` functions basically do absolutely nothing that wouldn't be trivial to write manually with the same one-liner wherever these methods are necessary imo.

<img width="664" alt="screen shot 2017-12-18 at 6 18 34 am" src="https://user-images.githubusercontent.com/523141/34103633-6e097d5a-e3bb-11e7-9909-310b4d8bfbb6.png">

<img width="347" alt="screen shot 2017-12-18 at 6 18 49 am" src="https://user-images.githubusercontent.com/523141/34103637-71d0ee6e-e3bb-11e7-9c01-572a22ba0ef2.png">

**Comment by niftylettuce** [comment]
you could use `delay` in place of `wait` btw

**Comment by Marsup** [comment]
Use an older version of boom, we're not going back, it's been debated to death in other repos.

**Comment by niftylettuce** [comment]
Can you provide links to the discussions in other repos?  Just because of lengthy debate does not mean it's solved.  This is a core problem with this package and it is clearly against npm principles.  To design a package based off other repos bad practice is not proper.

**Comment by Marsup** [comment]
It is not. All packages have been major-bumped in consequence of our requirement on node 8, don't want that, use old packages.

**Comment by niftylettuce** [comment]
You don't seem to realize how many other packages depend on Boom?

1807 packages depend on this

<img width="206" alt="screen shot 2017-12-18 at 9 40 42 am" src="https://user-images.githubusercontent.com/523141/34111374-89413826-e3d7-11e7-956a-dd4e432e0024.png">

It does not make sense to fix a core issue that is going to make 1807 packages need to upgrade their version of Node.js, for something that has **nothing to do with boom**?

**Comment by Marsup** [comment]
Then don't require the latest, what is so hard to understand about it ?

**Comment by niftylettuce** [comment]
This is pure laziness as a developer and community to do this to 1807 packages.  The features that would impose this version are not even relevant to this package.  Quite absurd.  If every package did this the entire npm community will fall apart more so than it may already have.

**Comment by Marsup** [comment]
No dependency package **needs** to upgrade, none at all. Upgrading to a major version requires due diligence of looking what happened to the project that's being bumped, blindly doing it can only result in what you describe and I would hardly put the blame on the project for my mistake.

As to why the decision was taken, it was
1) to nudge the community to move to what we think is a more modern ecosystem, not force anyone
2) just simpler for us to move the whole organization to this considering that most if not all the contributors are not corporate backed and we don't have the means 
3) not a bad decision considering that we would keep maintaining the older versions until it's safe to completely deprecate

Being angry, entitled and start insulting people doesn't make you more right.

**Comment by niftylettuce** [comment]
we will fork and republish instead

**Comment by Marsup** [comment]
This looks unreasonable but fine by us.

**Comment by hueniverse** [comment]
![capture_d_____cran_2017-12-18____16 18 07-fullpage](https://user-images.githubusercontent.com/56631/34122617-f1e8fb98-e3e1-11e7-914e-36d7f6adb043.png)

**Comment by hueniverse** [comment]
@niftylettuce You want to talk about proper process and policies? How about not deleting you side of a thread after wasting someone's time? I am not surprised you did that because this thread does make you look like a bit of an ass. Unfortunately, we have it saved...

I consider this action to be sufficiently hostile to ban someone from the hapijs organization so consider this your first and last warning. I have no tolerance whatsoever for people who waste the time of our contributors with an attitude of entitlement and hostility. And while others have raised similar issues in the past, no one has been such an asshole about it.

As for the actual issue, no one here did anything to hurt you or the npm ecosystem. You, out of your own free will, decided to upgrade your dependency of boom to a version that clearly followed semver above and beyond. We published a new major version when we required node v8 along with other interface breaking changes. The previous version works just fine and we have already communicated we will backport security and critical bug fixes as long as we officially support hapi v16 (which is for a while).

boom is part of the hapi.js ecosystem. It is maintained according to our community guidelines and principals. If you disagree with them, feel free to use something else. These are the same principals that also apply to how we communicate with each other.

Open source is a cesspool of entitlement, maintainer abuse, freeloading, and general douchebaggery. I will not have it here. You might feel this response is an over reaction (but maybe not since you erased the thread), but sometimes people have to be made an example of as a warning sign to others.

The hapi.js ecosystem is a safe place for people to collaborate and build amazing software. I intend to keep it that way.
