### ISSUE TITLE
Required node version increase is breaking

### ISSUE THREAD

**Issue by adanilev** [hapijs/boom#207]
Hi there,

This increased node version requirement turned out to be a breaking change for my project: https://github.com/hapijs/boom/commit/2790af39cb1dc0bce3b94e4ce75b1f046f7e29fa

We're building Lambda functions and use a package called [serverless-s3-local](https://github.com/ar90n/serverless-s3-local) which is dependent on [cryptiles](https://github.com/hapijs/cryptiles) which is dependent on boom. Lambdas run on Node 8.10 (which is the latest version that AWS offer) so we use that on our locals as well. Doing a yarn install today yielded this error:
```
error boom@7.2.1: The engine "node" is incompatible with this module. Expected version ">=8.12.0". Got "8.10.0"
error Found incompatible module
```

Not sure what the best solution is (or if you would really consider this "breaking"). Are there incompatible changes with 8.10? If not, perhaps consider relaxing the requirement to a range of versions? Or increasing the major version number?

My current workaround is to ignore engines when yarn install-ing: `yarn --ignore-engines`

Thanks and please let me know if any other information would be helpful. Kudos on keeping your repos up-to-date BTW 😃

**Comment by hueniverse** [comment]
In general, we do not officially support yarn. With npm, engine is informational only and we have been updating the engine value to the latest supported node version every few months to reflect what our CI environment is running.

Is the issue here your local yard deployment or is AWS actually blocking the code from running due to the engine change?

**Comment by johannes-scharlach** [comment]
So yarn does check the engines field during install and the installation aborts when it encounters a version requirement that's not satisfied.

This affects all `yarn install` s including adding or removing dependencies. Switching to npm is not really an option, as I do rely on some yarn features (namely workspaces and resolutions), so the only workarounds are either forcing the usage of an older version of boom (through yarn resolutions) or passing the `--ignore-engines` flag on every yarn installation.

We can argue about wether or not that's a useful feature (or if it should just be a warning) on yarn's side, but as of today I can't update my boom/bounce dependencies anymore due to this change.

I'd suggest keeping the engines version at the lowest that you can reasonably assume would work (i.e. >=8.0.0).

**Comment by hueniverse** [comment]
See: https://github.com/hapijs/hapi/issues/3859

I am sorry this is an inconvenience but that's how we maintain the hapi ecosystem, especially core modules. You can add the flag to ignore engines in your `.yarnrc` file too.
