### ISSUE TITLE
@hapi/boom error

### ISSUE THREAD

**Issue by xusai2014** [hapijs/boom#283]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): yes

#### Context

* *node version*: 14.16.0
* *module version with issue*: 9.1.2
* *last module version without issue*:  same 
* *environment* (e.g. node, browser, native):  node
* *used with* (e.g. hapi application, another framework, standalone, ...): nextjs dependency
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?

```js

```

Error is as below
```

/node_modules/@hapi/boom/lib/index.js:69
exports.Boom = class extends Error {
               ^
TypeError: Cannot assign to read only property 'Symbol(Symbol.hasInstance)' of function 'function Boom(message, options) {
        if (options === void 0) { options = {}; }
        var _this = this;
 ...<omitted>... }'
    at /node_modules/@hapi/boom/lib/index.js:92:32
    at Object.<anonymous> (/node_modules/@hapi/boom/lib/index.js:69:16)

```

**Comment by Nargonath** [comment]
The tests are successful on `node@14` on our part for the latest version so my guess is that the problem comes from the way `@hapi/boom` is used. From your stacktrace it seems perhaps something is trying to assign to the static method `Symbol.hasInstance` on the Boom prototype after it has been defined. 🤔 Did you share the full stacktrace?

**Comment by devinivy** [comment]
Seems like this may have become an inactive issue.  The only thing I have to add is that it sounds like you may be trying to bundle boom for the browser, which isn't officially supported by the module which is design for server settings.  But if you're intent on doing it, then it may require configuring your bundler to treat boom as a nodejs module rather than something pre-built for the browser.
